<?php
global $data_var;
$data_var = array(
  'main_title' => 'Animations',
  'subheading' => 'Bootstrap 5 Animations',
  'seo_title' => 'Bootstrap 5 Animations - examples & tutorial',
  'description' => 'Bootstrap 5 animations imitate motions for web elements. +70 animations generated by CSS only, work on every browser.',
  'url' => 'https://mdbootstrap.com/docs/standard/content-styles/animations/',
  'image' => 'https://mdbootstrap.com/wp-content/themes/mdbootstrap4/content-gh/en/_mdb5/standard/web/docs/content-styles/animations/animations.jpg',
  'video' => 'https://www.youtube.com/watch?v=c9B4TPnak1A',
);
